apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argocd
type: Opaque
stringData:
    email-username: <YOUR_EMAIL_USERNAME>
    email-password: <YOUR_EMAIL_PASSWORD>
