controller:
  replicas: 1

configs:
  secret:
    argocdServerAdminPassword: "${ARGOCD_ADMIN_PASSWORD_BCRYPT}" # real password is here in bcrypt format
  repositories:
    - url: "${ARGOCD_HELM_CHARTS_REPO}"
      name: "${ARGOCD_HELM_CHARTS_REPO_NAME}"
      type: git

server:
  replicas: 1
  service:
    type: NodePort  # Change from ClusterIP to NodePort
    nodePortHttp: 30080  # Optional: Specify the NodePort for HTTP (if needed)
    nodePortHttps: 30443  # Optional: Specify the NodePort for HTTPS (if needed)

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1
