controller:
  replicas: 1

configs:
  secret:
    argocdServerAdminPassword: "${ARGOCD_ADMIN_PASSWORD_BCRYPT}" # real password is here in bcrpyt format
  repositories:
    - url: git@github.com:yashrajgosavi/argo-cd-helm-charts.git
      name: argo-cd-helm-charts
      type: git

server:
  replicas: 1
  service:
    type: ClusterIP

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1