controller:
  replicas: 1

configs:
  secret:
    argocdServerAdminPassword: "${ARGOCD_ADMIN_PASSWORD_BCRYPT}"
  repositories:
    - url: "${ARGOCD_HELM_CHARTS_REPO}"
      name: "${ARGOCD_HELM_CHARTS_REPO_NAME}"
      type: git

server:
  replicas: 1
  service:
    type: LoadBalancer

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1
