apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-backend-prod
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
      revision: main
      files:
      - path: apps/**/values-prod.yaml
  template:
    metadata:
      name: '{{path.basename}}-prod'
    spec:
      project: product-prod
      source:
        helm:
          valueFiles:
          - values-prod.yaml
        path: '{{path}}'
        repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
        targetRevision: main
      destination:
        namespace: product-prod
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
