apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: product-backend-test
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
      revision: main
      directories:
      - path: apps/*
      - exclude: true      
        path: apps/backup/
  template:
    metadata:
      name: '{{path.basename}}-test'
    spec:
      project: product-test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        helm:
          valueFiles:
            - values-test.yaml
        repoURL: https://github.com/yashrajgosavi/argo-cd-helm-charts
        targetRevision: main
        path: '{{path}}'
      destination:
        name: in-cluster
        server: https://kubernetes.default.svc
        namespace: product-test